apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    {{- include "projet-etudiants.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.authService }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.images.authService.repository }}:{{ .Values.images.authService.tag }}"
          imagePullPolicy: {{ .Values.images.authService.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/authdb
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
