apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: ZXR1ZGlhbnRzX2Ri # "etudiants_db"
  POSTGRES_USER: cG9zdGdyZXM= # "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # "postgres"
