global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'etudiant-service'
    static_configs:
      - targets: ['etudiant-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'grading-service'
    static_configs:
      - targets: ['grading-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8083']
    metrics_path: '/actuator/prometheus'
